spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transactiondb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
   
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/.well-known/jwks.json


server:
  port: 8091


application:
  name: transaction-service