spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transactiondb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
   
server:
  port: 8091


account:
  service:
    url: http://localhost:8084

application:
  name: transaction-service